# azure-pipelines.yml
trigger: none

pool:
  name: performance-test-linux

parameters:
  - name: "API_SUBSCRIPTION_KEY"
    displayName: "API_SUBSCRIPTION_KEY"
    type: string
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
      - "prod"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "load"
      - "spike"
      - "stress"
      - "soak"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - calculator_getFees
      - calculator_getFeesByPsp
      - calculator-load-test

steps:
  - script: |
      cd ./performance-tests
      docker pull grafana/k6
    displayName: Pull k6 image

  - script: |
      docker run \
        -v ${PWD}:/script \
        -e API_SUBSCRIPTION_KEY=${{ parameters.API_SUBSCRIPTION_KEY }} \
        -e VARS=${{ parameters.ENVIRONMENT }}.environment.json \
        -e TEST_TYPE=./test-types/${{ parameters.TEST_TYPE }}.json \
        -e K6_OUT=influxdb=https://api.dev.platform.pagopa.it/shared/influxdb/v1/k6
        grafana/k6 run /script/${{ parameters.SCRIPT }}.js \
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}
