version: '3.3'
services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - API_SUBSCRIPTION_KEY=${API_SUBSCRIPTION_KEY}
      - VARS=/scripts/${ENV}.environment.json
      - TEST_TYPE=/scripts/test-types/${TEST_TYPE}.json
      - K6_OUT=influxdb=http://nginx:8086/${DB_NAME}
    command: run /scripts/${SCRIPT}.js
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

