microservice-chart:
  namespace: "afm"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaafmcalculator
    tag: "0.0.3-2"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuuat.afm.internal.uat.platform.pagopa.it"
    path: /pagopa-afm-calculator-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 5
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 60 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaafmcalculator' # required to show cloud role name in application insights
    DB_HOST: pagopaafmcalculatordata-microservice-chart:4000
    CACHE_SIZE: '1000'
    CACHE_EXPIRATION_TIME: '3m'
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: ai-u-connection-string
  keyvault:
    name: "pagopa-u-afm-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
