microservice-chart:
  namespace: "afm"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-afm-calculator
    tag: "2.9.0-5-PAGOPA-1386-afm-issue-shuffle-order-response"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.afm.internal.uat.platform.pagopa.it"
    path: /pagopa-afm-calculator-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.75"
    limits:
      memory: "1024Mi"
      cpu: "1.0"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 60 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  fileConfig: {}
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaafmcalculator' # required to show cloud role name in application insights
    ENV: 'uat'
    APP_LOGGING_LEVEL: 'DEBUG'
    CACHE_SIZE: '1000'
    CACHE_EXPIRATION_TIME: '3m'
    CACHE_ENABLED: 'true'
    COSMOS_URI: https://pagopa-u-weu-afm-marketplace-cosmos-account.documents.azure.com:443/
    ISSUER_RANGE_TABLE: 'pagopauweuafmsaissuerrangetable'
    AMOUNT_THRESHOLD: '0'
    ID_PSP_POSTE: 'BPPIITRRXXX'
    AMEX_ABI: 'AMREX'
    OTEL_SERVICE_NAME: "pagopa-afm-calculator"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: ai-u-connection-string
    COSMOS_KEY: afm-marketplace-u-cosmos-pkey
    AFM_SA_CONNECTION_STRING: afm-u-sa-connection-string
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
  keyvault:
    name: "pagopa-u-afm-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-afm-calculator
        tag: "2.7.3"
        pullPolicy: Always
      envConfig:
      envSecret:
