microservice-chart:
  namespace: "afm"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-afm-utils
    tag: "0.7.0-6-PAGOPA-1305-invalidare-i-bundle-settando-la-data-di-fine-validita-per-psp"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuprod.afm.internal.platform.pagopa.it"
    path: /pagopa-afm-utils-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1Gi"
      cpu: "0.3"
    limits:
      memory: "1.5Gi"
      cpu: "1"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 1
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaafmutils' # required to show cloud role name in application insights
    ENV: 'prod'
    APP_LOGGING_LEVEL: "INFO"
    CACHE_SIZE: '10000'
    CACHE_EXPIRATION_TIME: '5m'
    CONFIGURATION_TRIGGER: "0 0 12 * * ?"
    AFM_MARKETPLACE_HOST: https://api.platform.pagopa.it/afm/marketplace-service/v1
    AFM_MARKETPLACE_RETRY_MAX_ATTEMPTS: "1"
    AFM_MARKETPLACE_RETRY_MAX_DELAY: "2000"
    COSMOS_URI: https://pagopa-p-weu-afm-marketplace-cosmos-account.documents.azure.com:443/
    COSMOS_DATABASE: 'db'
    COSMOS_QUERY_METRICS: 'false'
    CDI_CONTAINER_NAME: 'cdis'
    OTEL_SERVICE_NAME: "pagopa-afm-utils"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: ai-p-connection-string
    AFM_MARKETPLACE_SUBSCRIPTION_KEY: afm-marketplace-subscription-key
    COSMOS_KEY: afm-marketplace-p-cosmos-pkey
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
  keyvault:
    name: "pagopa-p-afm-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-afm-utils
        tag: "0.7.0-1-PAGOPA-1305-invalidare-i-bundle-settando-la-data-di-fine-validita-per-psp"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
