microservice-chart:
  namespace: "afm"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaafmcalculator
    tag: "2.5.5"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weudev.afm.internal.dev.platform.pagopa.it"
    path: /pagopa-afm-calculator-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 60 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaafmcalculator' # required to show cloud role name in application insights
    ENV: 'azure-dev'
    APP_LOGGING_LEVEL: 'DEBUG'
    CACHE_SIZE: '1000'
    CACHE_EXPIRATION_TIME: '3m'
    CACHE_ENABLED: 'true'
    COSMOS_URI: https://pagopa-d-weu-afm-marketplace-cosmos-account.documents.azure.com:443/
    ISSUER_RANGE_TABLE: 'pagopadweuafmsaissuerrangetable'
    AMOUNT_THRESHOLD: '0'
    ELASTIC_APM_SERVICE_NAME: pagopa-afm-calculator
    ELASTIC_APM_APPLICATION_PACKAGES: it.gov.pagopa.afm.calculator
    ELASTIC_APM_SERVER_URL: http://quickstart-apm-http.elastic-system.svc:8200
    ELASTIC_APM_LOG_SENDING: 'true'
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    COSMOS_KEY: afm-marketplace-d-cosmos-pkey
    AFM_SA_CONNECTION_STRING: afm-d-sa-connection-string
    ELASTIC_APM_SECRET_TOKEN: elastic-apm-secret-token
  keyvault:
    name: "pagopa-d-afm-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: 2.5.4-5-kibana
