microservice-chart:
  namespace: "afm"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaafmcalculator
    tag: "0.0.1-11"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuprod.afm.internal.platform.pagopa.it"
    path: /pagopa-afm-calculator-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "500Mi"
      cpu: "350m"
    limits:
      memory: "500Mi"
      cpu: "350m"
  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: b9fc9419-6097-45fe-9f74-ba0641c91912
          resourceGroupName: pagopa-p-afm-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-p-afm-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"
  envConfig:
    CACHE_SIZE: '1000'
    CACHE_EXPIRATION_TIME: '10s'
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: ai-p-connection-string
  keyvault:
    name: "pagopa-p-afm-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
