microservice-chart:
  namespace: "afm"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaafmcalculator
    tag: "2.5.4"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weuuat.afm.internal.uat.platform.pagopa.it"
    path: /pagopa-afm-calculator-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.75"
    limits:
      memory: "1024Mi"
      cpu: "1.0"
  autoscaling:
    enable: true
    minReplica: 6
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 60 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaafmcalculator' # required to show cloud role name in application insights
    ENV: 'azure-uat'
    APP_LOGGING_LEVEL: 'DEBUG'
    CACHE_SIZE: '1000'
    CACHE_EXPIRATION_TIME: '3m'
    CACHE_ENABLED: 'true'
    COSMOS_URI: https://pagopa-u-weu-afm-marketplace-cosmos-account.documents.azure.com:443/
    ISSUER_RANGE_TABLE: 'pagopauweuafmsaissuerrangetable'
    AMOUNT_THRESHOLD: '0'
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: ai-u-connection-string
    COSMOS_KEY: afm-marketplace-u-cosmos-pkey
    AFM_SA_CONNECTION_STRING: afm-u-sa-connection-string
  keyvault:
    name: "pagopa-u-afm-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: 2.5.4-1-kibana
