name: Integration Tests

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Run Integration Tests
        run: |
          cd ./integration-test/src
          export subkey=${{ secrets.SUBKEY }}
          yarn install
          yarn test${{( github.event.inputs == null && ':dev') || ':${{inputs.environment}}' }}
