name: Open a PR in Infra repository

on:
  pull_request:
    branches:
      - main


  workflow_dispatch:

jobs:
  pull-request:
#    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update OpenApi
        run: |
          sh ./openapi/generate_openapi.sh local

      - name: Commit & Push changes
        run: |
          git config --global user.name 'pagopa-github-bot' 
          git config --global user.email 'github-bot@pagopa.it'
          git add -A
          git commit -m "Auto Update Openapi and Swagger [skip ci]"
          git push

      # prepare openapi template for infra repo
      - run: |
          mkdir -p "${GITHUB_WORKSPACE}/infra"
          jq  '."servers"[0]."url" |= "${host}"' "${GITHUB_WORKSPACE}/openapi/openapi.json" > "${GITHUB_WORKSPACE}/infra/_openapi.json.tpl"

      # open a PR on infra repo
      - name: Create pull request
        uses: jacopocarlini/action-pull-request-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'infra'
          destination_repo: 'pagopa/pagopa-infra'
          destination_folder: 'src/domains/afm-app/api/calculator-service/v1'
          destination_base_branch: 'main'
          destination_head_branch: 'AFM-Calculator-swagger-update'
          user_email: 'github-bot@pagopa.it'
          user_name: 'pagopa-github-bot'
          allow_force_push: 'true'

      # prepare openapi template for infra repo
      - run: |
          mkdir -p "${GITHUB_WORKSPACE}/infra"
          jq  '."servers"[0]."url" |= "${host}"' "${GITHUB_WORKSPACE}/openapi/openapi-node.json" > "${GITHUB_WORKSPACE}/infra/_openapi.json.tpl"

      # open a PR on infra repo
      - name: Create pull request
        uses: jacopocarlini/action-pull-request-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'infra'
          destination_repo: 'pagopa/pagopa-infra'
          destination_folder: 'src/domains/afm-app/api/calculator-service/node/v1'
          destination_base_branch: 'main'
          destination_head_branch: 'AFM-Calculator-Node-swagger-update'
          user_email: 'github-bot@pagopa.it'
          user_name: 'pagopa-github-bot'
          allow_force_push: 'true'
