name: Update Code

on:
  pull_request:
    branches:
      - main
  issue_comment:
    types: [created, edited]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    if: ${{ github.event.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"

      - uses: actions/github-script@v6.3.3
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context);
            var comments = await github.rest.issues.listComments({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
            });
            for (const comment of comments.data) {
              console.log(comment);
              if (comment.body.includes('Comment this PR with')){
                github.rest.issues.deleteComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                })
              }
            }
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Comment this PR with *update_code* to update `openapi.json` and to format the code'
            })
  

  update:
    name: Update Openapi and Formatting
    runs-on: ubuntu-latest
    if: ${{ github.event.event_name == 'issue_comment' && contains('update_code', github.event.comment.body) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Update OpenApi and Swagger files
        run: |
          cd ./openapi
          sh ./generate_openapi.sh

      - name: Formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          commit-message: "Google Java format [skip ci]"
