name: Update Openapi

# Controls when the workflow will run
on:
  pull_request_target:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-18.04 # needed for cosmosdb container
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update OpenApi
        run: |
          sh ./openapi/generate_openapi.sh local

      - name: Commit & Push changes
        run: |
          git config --global user.name 'pagopa-github-bot' 
          git config --global user.email 'github-bot@pagopa.it'
          git add -A
          git commit -m "Auto Update Openapi and Swagger [skip ci]" || true
          git push
