name: Update Code

on:
  issue_comment:
    types: [created, edited]


permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update:
    name: Update Openapi and Formatting
    runs-on: ubuntu-latest
    environment:
      name: dev
    if: ${{ contains(github.event.comment.body, 'update_code') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN_GITHUB }}

      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Run Service on Docker
        shell: bash
        run: |
          cd ./docker
          chmod +x ./run_docker.sh
          ./run_docker.sh local

      - name: Update OpenApi/Swagger file
        run: |
          cd ./openapi
          chmod +x ./generate_openapi.sh
          ./generate_openapi.sh

      - name: Formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          commit-message: "Google Java format [skip ci]"

  notify:
    needs: [ update ]
    runs-on: ubuntu-latest
    name: Notify
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Notify if Failure
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var comments = await github.rest.issues.listComments({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
            });
            for (const comment of comments.data) {
              if (comment.body.includes('Update Code is failed. Please retry.')){
                github.rest.issues.deleteComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id
                })
              }
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Update Code is failed. Please retry.'
            })
            core.setFailed('Update Code is failed. Please retry.')
  
  
  

  delete_github_deployments:
    runs-on: ubuntu-latest
    needs: update
    if: ${{ always() }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Delete Previous deployments
        uses: actions/github-script@v6
        env:
          SHA_HEAD: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha}}
        with:
          script: |
            const { SHA_HEAD } = process.env

            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: SHA_HEAD
            });
            await Promise.all(
              deployments.data.map(async (deployment) => {
                await github.rest.repos.createDeploymentStatus({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id,
                  state: 'inactive'
                });
                return github.rest.repos.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id
                });
              })
            );
